mkdir /home/pi/project/frontend/log/
touch /home/pi/project/frontend/log/logfile
mkdir /home/pi/project/api/log/
touch /home/pi/project/api/log/logfile
mkdir /home/pi/project/motor_control_module/log/
touch /home/pi/project/motor_control_module/log/logfile
mkdir /home/pi/project/cam_motor_module/log/
touch /home/pi/project/cam_motor_module/log/logfile
mkdir /home/pi/project/object_detection_module/log/
touch /home/pi/project/object_detection_module/log/logfile